<?php
/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-21 at 00:21:53.
 */
class conceptTest extends PHPUnit_Framework_TestCase
{
    /**
     * @var concept
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new concept;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
