<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-21 at 00:21:58.
 */
class PHPMailerTest extends PHPUnit_Framework_TestCase {

    /**
     * @var PHPMailer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new PHPMailer;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers PHPMailer::IsHTML
     * @todo   Implement testIsHTML().
     */
    public function testIsHTML() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::IsSMTP
     * @todo   Implement testIsSMTP().
     */
    public function testIsSMTP() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::IsMail
     * @todo   Implement testIsMail().
     */
    public function testIsMail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::IsSendmail
     * @todo   Implement testIsSendmail().
     */
    public function testIsSendmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::IsQmail
     * @todo   Implement testIsQmail().
     */
    public function testIsQmail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddAddress
     * @todo   Implement testAddAddress().
     */
    public function testAddAddress() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddCC
     * @todo   Implement testAddCC().
     */
    public function testAddCC() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddBCC
     * @todo   Implement testAddBCC().
     */
    public function testAddBCC() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddReplyTo
     * @todo   Implement testAddReplyTo().
     */
    public function testAddReplyTo() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::Send
     * @todo   Implement testSend().
     */
    public function testSend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SendmailSend
     * @todo   Implement testSendmailSend().
     */
    public function testSendmailSend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::MailSend
     * @todo   Implement testMailSend().
     */
    public function testMailSend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SmtpSend
     * @todo   Implement testSmtpSend().
     */
    public function testSmtpSend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SmtpConnect
     * @todo   Implement testSmtpConnect().
     */
    public function testSmtpConnect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SmtpClose
     * @todo   Implement testSmtpClose().
     */
    public function testSmtpClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SetLanguage
     * @todo   Implement testSetLanguage().
     */
    public function testSetLanguage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddrAppend
     * @todo   Implement testAddrAppend().
     */
    public function testAddrAppend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddrFormat
     * @todo   Implement testAddrFormat().
     */
    public function testAddrFormat() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::WrapText
     * @todo   Implement testWrapText().
     */
    public function testWrapText() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SetWordWrap
     * @todo   Implement testSetWordWrap().
     */
    public function testSetWordWrap() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::CreateHeader
     * @todo   Implement testCreateHeader().
     */
    public function testCreateHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::CreateBody
     * @todo   Implement testCreateBody().
     */
    public function testCreateBody() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::GetBoundary
     * @todo   Implement testGetBoundary().
     */
    public function testGetBoundary() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::EndBoundary
     * @todo   Implement testEndBoundary().
     */
    public function testEndBoundary() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SetMessageType
     * @todo   Implement testSetMessageType().
     */
    public function testSetMessageType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::HeaderLine
     * @todo   Implement testHeaderLine().
     */
    public function testHeaderLine() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::TextLine
     * @todo   Implement testTextLine().
     */
    public function testTextLine() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddAttachment
     * @todo   Implement testAddAttachment().
     */
    public function testAddAttachment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AttachAll
     * @todo   Implement testAttachAll().
     */
    public function testAttachAll() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::EncodeFile
     * @todo   Implement testEncodeFile().
     */
    public function testEncodeFile() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::EncodeString
     * @todo   Implement testEncodeString().
     */
    public function testEncodeString() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::EncodeHeader
     * @todo   Implement testEncodeHeader().
     */
    public function testEncodeHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::EncodeQP
     * @todo   Implement testEncodeQP().
     */
    public function testEncodeQP() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::EncodeQ
     * @todo   Implement testEncodeQ().
     */
    public function testEncodeQ() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddStringAttachment
     * @todo   Implement testAddStringAttachment().
     */
    public function testAddStringAttachment() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddEmbeddedImage
     * @todo   Implement testAddEmbeddedImage().
     */
    public function testAddEmbeddedImage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::InlineImageExists
     * @todo   Implement testInlineImageExists().
     */
    public function testInlineImageExists() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearAddresses
     * @todo   Implement testClearAddresses().
     */
    public function testClearAddresses() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearCCs
     * @todo   Implement testClearCCs().
     */
    public function testClearCCs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearBCCs
     * @todo   Implement testClearBCCs().
     */
    public function testClearBCCs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearReplyTos
     * @todo   Implement testClearReplyTos().
     */
    public function testClearReplyTos() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearAllRecipients
     * @todo   Implement testClearAllRecipients().
     */
    public function testClearAllRecipients() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearAttachments
     * @todo   Implement testClearAttachments().
     */
    public function testClearAttachments() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ClearCustomHeaders
     * @todo   Implement testClearCustomHeaders().
     */
    public function testClearCustomHeaders() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::SetError
     * @todo   Implement testSetError().
     */
    public function testSetError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::RFCDate
     * @todo   Implement testRFCDate().
     */
    public function testRFCDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ServerVar
     * @todo   Implement testServerVar().
     */
    public function testServerVar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::ServerHostname
     * @todo   Implement testServerHostname().
     */
    public function testServerHostname() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::Lang
     * @todo   Implement testLang().
     */
    public function testLang() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::IsError
     * @todo   Implement testIsError().
     */
    public function testIsError() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::FixEOL
     * @todo   Implement testFixEOL().
     */
    public function testFixEOL() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers PHPMailer::AddCustomHeader
     * @todo   Implement testAddCustomHeader().
     */
    public function testAddCustomHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
