<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-10-21 at 00:21:57.
 */
class SMTPTest extends PHPUnit_Framework_TestCase {

    /**
     * @var SMTP
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new SMTP;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers SMTP::Connect
     * @todo   Implement testConnect().
     */
    public function testConnect() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Authenticate
     * @todo   Implement testAuthenticate().
     */
    public function testAuthenticate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Connected
     * @todo   Implement testConnected().
     */
    public function testConnected() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Close
     * @todo   Implement testClose().
     */
    public function testClose() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Data
     * @todo   Implement testData().
     */
    public function testData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Expand
     * @todo   Implement testExpand().
     */
    public function testExpand() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Hello
     * @todo   Implement testHello().
     */
    public function testHello() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::SendHello
     * @todo   Implement testSendHello().
     */
    public function testSendHello() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Help
     * @todo   Implement testHelp().
     */
    public function testHelp() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Mail
     * @todo   Implement testMail().
     */
    public function testMail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Noop
     * @todo   Implement testNoop().
     */
    public function testNoop() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Quit
     * @todo   Implement testQuit().
     */
    public function testQuit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Recipient
     * @todo   Implement testRecipient().
     */
    public function testRecipient() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Reset
     * @todo   Implement testReset().
     */
    public function testReset() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Send
     * @todo   Implement testSend().
     */
    public function testSend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::SendAndMail
     * @todo   Implement testSendAndMail().
     */
    public function testSendAndMail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::SendOrMail
     * @todo   Implement testSendOrMail().
     */
    public function testSendOrMail() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Turn
     * @todo   Implement testTurn().
     */
    public function testTurn() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::Verify
     * @todo   Implement testVerify().
     */
    public function testVerify() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers SMTP::get_lines
     * @todo   Implement testGet_lines().
     */
    public function testGet_lines() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
